name: Track Collaborator Changes

on:
  push:
    branches:
      - main

jobs:
  track-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log Collaborator Changes
        run: |
          # Get a list of collaborator emails
          collaborators=$(gh api repos/${{ github.repository }}/collaborators --jq '.[].email')

          # Log only commits made by collaborators
          git log --pretty=format:'%h - %an, %ar : %s' ${{ github.event.before }}..${{ github.sha }} | grep -f <(echo "$collaborators") >> changes.log

          # Print the contents of the log file
          cat changes.log

      - name: Upload Log File
        uses: actions/upload-artifact@v3
        with:
          name: collaborator-changes-log
          path: changes.log

